server:
  port: 6030
spring:
  application:
    name: es-service
  data:
    elasticsearch:
      cluster-name: elasticsearch  # 集群名称
      cluster-nodes: 127.0.0.1:9300 # 集群地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #服务注册的地址
  instance:
    instance-id: es-server:6030
    prefer-ip-address: true