server:
  port:8050
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #服务注册的地址
  instance:
    instance-id: file-server:8050
    prefer-ip-address: true

spring:
  application:
    name: file-server
